/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'home', // document id
      label: 'Start', // sidebar label
    },
    {
      type: 'category',
      label: 'Accounts & Passwörter',
      items: [
        'accounts/anmelden', 
        'accounts/passwort-aendern'
      ],
    },
    'beitraege-erstellen',
    {
      type: 'category',
      label: 'Seiten bearbeiten',
      items: [
        'Seiten bearbeiten/seiten-bearbeiten', 
        'Seiten bearbeiten/seiten-erstellen',
        'Seiten bearbeiten/seitenleisten-bearbeiten'
      ],
    },
    {
      type: 'doc',
      id: 'uebersetzungen-bearbeiten', // document id
      label: 'Übersetzungen bearbeiten', // sidebar label
    },
    'galerie',
    'kalender',
    'beschlussdatenbank',
    
    {
      type: 'category',
      label: 'Bettenbörse',
      items: [
        {
          type: 'doc',
          id: 'bettenboerse/verwaltung',
          label: 'Verwaltung der Bettenbörse',
        },
        {
          type: 'doc',
          id: 'bettenboerse/einrichtung',
          label: 'Einrichtung des Plugins',
        },
        {
          type: 'doc',
          id: 'bettenboerse/entwickler',
          label: 'Entwicklerinformationen',
        },
      ],
    },
  ],
   
};

module.exports = sidebars;
