name: Deploy to FTP

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - name: Build website
        run: |
          npm ci
          npm run build
      - name: Upload ftp
        uses: genietim/ftp-action@9aec41ec4f779cdb6d7f20ef6d0edbf094a7a0b4
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "build"
          remoteDir: "/"
